services:
  - type: web
    name: digital-coupon
    env: php
    buildCommand: |
      composer install
      npm install
      npm run build
      php artisan migrate:fresh --seed --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
